/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.util.List;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Slovo;
import operacija.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author vldmrk
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private static int pokusaji = 0;
    private static int pogodjeni = 0;

    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        pokreniKl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldKlSlovo1 = new javax.swing.JTextField();
        jTextFieldKlSlovo2 = new javax.swing.JTextField();
        jTextFieldKlSlovo3 = new javax.swing.JTextField();
        jTextFieldKlSlovo4 = new javax.swing.JTextField();
        jTextFieldKlSlovo5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPogadjanje = new javax.swing.JTextField();
        jButtonPogodi = new javax.swing.JButton();
        jLabelKoriscenaSlova = new javax.swing.JLabel();
        jLabelBrPokusaja = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonPokreni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1. slovo");

        jLabel2.setText("2. slovo");

        jLabel3.setText("3. slovo");

        jLabel4.setText("4. slovo");

        jLabel5.setText("5. slovo");

        jButtonPogodi.setText("POGODI");
        jButtonPogodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPogodiActionPerformed(evt);
            }
        });

        jLabelKoriscenaSlova.setText("Korišćena slova:");

        jLabelBrPokusaja.setText("Preostali broj pokušaja: ");

        jLabel6.setText("slovo");

        jButtonPokreni.setText("POKRENI IGRU");
        jButtonPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextFieldPogadjanje, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPogodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextFieldKlSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldKlSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldKlSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldKlSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jTextFieldKlSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKoriscenaSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBrPokusaja, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKlSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKlSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKlSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKlSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKlSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPogadjanje, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPogodi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jLabelKoriscenaSlova)
                .addGap(27, 27, 27)
                .addComponent(jLabelBrPokusaja)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniActionPerformed

        KlijentskiZahtev kz = new KlijentskiZahtev(null, Operacije.POKRENI_IGRU);
        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean pokrenuto = (boolean) so.getOdgovor();
        if (pokrenuto) {
            jTextFieldPogadjanje.setEditable(true);
            jButtonPogodi.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "NIJE POKRENUT SERVER", "SERVER SE NIJE POKRENUO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPokreniActionPerformed

    private void jButtonPogodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPogodiActionPerformed
        pokusaji++;
        if (pokusaji <= 10) {
            char slovo = jTextFieldPogadjanje.getText().toUpperCase().charAt(0);
            jTextFieldPogadjanje.setText("");
            KlijentskiZahtev kz = new KlijentskiZahtev(slovo, Operacije.POGODI_SLOVO);
            Komunikacija.getInstance().posaljiZahtev(kz);
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            obradiOdgovor(so);
        } else {
            JOptionPane.showMessageDialog(this, "NEMA POKUSAJA", "NEMAS VISE POKUSAJA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPogodiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlijentskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlijentskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPogodi;
    private javax.swing.JButton jButtonPokreni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBrPokusaja;
    private javax.swing.JLabel jLabelKoriscenaSlova;
    private javax.swing.JTextField jTextFieldKlSlovo1;
    private javax.swing.JTextField jTextFieldKlSlovo2;
    private javax.swing.JTextField jTextFieldKlSlovo3;
    private javax.swing.JTextField jTextFieldKlSlovo4;
    private javax.swing.JTextField jTextFieldKlSlovo5;
    private javax.swing.JTextField jTextFieldPogadjanje;
    // End of variables declaration//GEN-END:variables

    public void pokreniKlijent(String rec) {

        jTextFieldKlSlovo1.setText(String.valueOf(rec.charAt(0)));
        jTextFieldKlSlovo2.setText(String.valueOf(rec.charAt(1)));
        jTextFieldKlSlovo3.setText(String.valueOf(rec.charAt(2)));
        jTextFieldKlSlovo4.setText(String.valueOf(rec.charAt(3)));
        jTextFieldKlSlovo5.setText(String.valueOf(rec.charAt(4)));

    }

    private void pokreniKl() {
        jTextFieldKlSlovo1.setEditable(false);
        jTextFieldKlSlovo2.setEditable(false);
        jTextFieldKlSlovo3.setEditable(false);
        jTextFieldKlSlovo4.setEditable(false);
        jTextFieldKlSlovo5.setEditable(false);
        jTextFieldPogadjanje.setEditable(false);
        jButtonPogodi.setEnabled(false);
    }

    private void obradiOdgovor(ServerskiOdgovor so) {
        List<Slovo> slova = (List<Slovo>) so.getOdgovor();
        if (slova.isEmpty()) {
            return;
        }
        for (Slovo s : slova) {
            pogodjeni++;
            switch (s.getPozicija()) {
                case 1:
                    jTextFieldKlSlovo1.setText(String.valueOf(s.getKarakter()));
                    break;
                case 2:
                    jTextFieldKlSlovo2.setText(String.valueOf(s.getKarakter()));
                    break;
                case 3:
                    jTextFieldKlSlovo3.setText(String.valueOf(s.getKarakter()));
                    break;
                case 4:
                    jTextFieldKlSlovo4.setText(String.valueOf(s.getKarakter()));
                    break;
                case 5:
                    jTextFieldKlSlovo5.setText(String.valueOf(s.getKarakter()));
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }
}
